name: Build and Release on linux 
on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  pyinstaller-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync  

      - name: Build
        run: |
          uv run pyinstaller --onefile -w --name=ACG_Photo_Get-linux-x86_64 gui_for_desktop.py

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
