name: Build exe for ACG_Photo_get

permissions:
  contents: write

# 触发条件：当推送到 main 分支，或推送以 'v' 开头的标签时触发
on:
  push:
    tags:
      - "v*"

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install uv 
          uv sync

      - name: Build exe
        run: |
          uv run pyinstaller --onefile -w --name=ACG_Photo_Get-windows-x86_64 gui.py

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/ACG_Photo_Get-windows-x86_64.exe
